// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDGYWHF4YJhQDBMgCZ4H-1kax8s7ht7jCk',
    appId: '1:196726378414:web:2db7aaabf796b73868423f',
    messagingSenderId: '196726378414',
    projectId: 'rafeek-eldarb',
    authDomain: 'rafeek-eldarb.firebaseapp.com',
    storageBucket: 'rafeek-eldarb.firebasestorage.app',
    measurementId: 'G-BVV4BSJY1X',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBrStRPzWIOM976d429SU6TwaikIrpMfZk',
    appId: '1:196726378414:android:8a6fb107f55c632f68423f',
    messagingSenderId: '196726378414',
    projectId: 'rafeek-eldarb',
    storageBucket: 'rafeek-eldarb.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDUEPUa5HTzhGp4KLZcTh4QNlPUriB2wvg',
    appId: '1:196726378414:ios:717a4244f31670a868423f',
    messagingSenderId: '196726378414',
    projectId: 'rafeek-eldarb',
    storageBucket: 'rafeek-eldarb.firebasestorage.app',
    iosBundleId: 'com.CrowEye.rafeekEldarb',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDGYWHF4YJhQDBMgCZ4H-1kax8s7ht7jCk',
    appId: '1:196726378414:web:af55fc44bd0d47f568423f',
    messagingSenderId: '196726378414',
    projectId: 'rafeek-eldarb',
    authDomain: 'rafeek-eldarb.firebaseapp.com',
    storageBucket: 'rafeek-eldarb.firebasestorage.app',
    measurementId: 'G-JSWDNNCTC7',
  );
}
